events {
    worker_connections 1024;
}

http {
    # Скрываем версию nginx(тк она может содержать уязвимости, что упростит злоумышленнику задачу по подбору эксплойта)
    server_tokens off;   

    server {
        listen 80;
        server_name site1.local;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name site1.local;

        ssl_certificate /etc/nginx/certs/localhost+2.pem;
        ssl_certificate_key /etc/nginx/certs/localhost+2-key.pem;

        location = /index.html {
            # Защита от clickjacking (блок iframe для сторонних сайтов)
            add_header X-Frame-Options "DENY"; 
            alias /static/index.html;
        }

        location /img/ {
            alias /static/assets/;
        }

        location / {
            # Защита от XSS
            add_header X-XSS-Protection "1; mode=block";    
            # MIME-sniffing защита
            add_header X-Content-Type-Options "nosniff";
            proxy_pass http://node:3000;
        }
    }


    server {
        listen 80;
        server_name site2.local;

        location /{
            return 200 "site2";
        }

    }
}
